### ISSUE TITLE
[Discussion] Update to Identity Framework and don't depend on social media log ins

### ISSUE THREAD

**Issue by codercampos** [developersdo/emplea_do#24]
I have noticed that the site uses social media providers to log in users. Is there any way to create a login / sign up feature that does not depend on social media providers.

I know, in practice, it's easy to use your social media but I think We have to support the "old-reliable" login / sign up process. Also, for testing in a local environment, We won't need social keys to test new feature.

**Comment by eatskolnikov** [comment]
Sorry mate, just social media for now.
