### ISSUE TITLE
As a user I want to be able to confirm posts

### ISSUE THREAD

**Issue by eatskolnikov** [developersdo/emplea_do#3]
Right now we are using Slack to confirm posts. 
We could either:
1. Keep slack and move it to a private channel in the emplea.do slack
2. Move this confirmation to teams

**Comment by RaulMonteroC** [comment]
I prefer using a slack private channel with a small no. of reviewers. From my point of view this lowers the entry barrier for new reviewers and as such allows faster response to job post updates.

**Comment by eatskolnikov** [comment]
In the end we moved it to the slack of this project, the community will be the moderators of the posts
