### ISSUE TITLE
Resultados de búsqueda

### ISSUE THREAD

**Issue by eatskolnikov** [developersdo/emplea_do#32]
Basado en este template
http://codeminifier.com/workio-job-board-template/workio/verticle-large-job.html

![Screen Shot 2019-08-22 at 9 40 34 AM](https://user-images.githubusercontent.com/1693000/63519422-e9653600-c4c0-11e9-8c37-d621e59d76e7.png)

**Comment by eatskolnikov** [comment]
@HommyDeJ .

**Comment by HommyDeJ** [comment]
Ayer hice pr.
