### ISSUE TITLE
Detalles de trabajo

### ISSUE THREAD

**Issue by eatskolnikov** [developersdo/emplea_do#33]
Basado en este template

http://codeminifier.com/workio-job-board-template/workio/job-detail.html
![Screen Shot 2019-08-22 at 9 41 22 AM](https://user-images.githubusercontent.com/1693000/63519468-069a0480-c4c1-11e9-9562-c9d3f5697c53.png)

**Comment by HommyDeJ** [comment]
.

**Comment by eatskolnikov** [comment]
Muy económico tu comentario @HommyDeJ 😅
