### ISSUE TITLE
Listado de empleadores

### ISSUE THREAD

**Issue by eatskolnikov** [developersdo/emplea_do#34]
Basado en este template
http://codeminifier.com/workio-job-board-template/workio/grid-employers.html

![Screen Shot 2019-08-22 at 9 42 55 AM](https://user-images.githubusercontent.com/1693000/63519592-406b0b00-c4c1-11e9-98a8-5213c00ea74a.png)

**Comment by HommyDeJ** [comment]
.

**Comment by DannyFeliz** [comment]
@HommyDeJ Puedes hacerle un watch a los issues sin gustas 😅
