### ISSUE TITLE
Configurar autenticación

### ISSUE THREAD

**Issue by eatskolnikov** [developersdo/emplea_do#49]
Vamosa configurarlo usando OWIN para .net core e integraremos estos servicios por ahora:

- [x] Google #48
- [x] Linkedin
- [x] Microsoft
- [x] Facebook
- [ ] Github

**Comment by eatskolnikov** [comment]
@christianrd 
¿has tenido algún impedimento? 

Mira esta referencia https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/?view=aspnetcore-2.2&tabs=visual-studio

Solo tienes que configurar el login/registro con un botón:
- El alcance es que se haga el redirect correctamente y tengas la información del perfil de la persona en memoria. 
- No tienes que acceder a la base de datos
- No tienes que crear usuarios

**Comment by eatskolnikov** [comment]
@christianrd esto se relaciona con el issue #55 pero no te preocupes por la parte visual, solo configura el owin. Si tienes algún impedimento podemos hacer pair hoy o mañana, escribeme.

**Comment by christianrd** [comment]
@eatskolnikov entendido, te escribo por slack...

**Comment by eatskolnikov** [comment]
@christianrd ¿algún impedimento?

**Comment by christianrd** [comment]
@eatskolnikov solo el tiempo 👀

**Comment by eatskolnikov** [comment]
@christianrd ¿has avanzado algo?

**Comment by Cesarlachapelle** [comment]
@christianrd puedo darte una mano, solo grita si necesitas ayuda.

**Comment by christianrd** [comment]
@Cesarlachapelle bien, te escribo por slack
