### ISSUE TITLE
Permitir hacer preview de empleos no aprobados

### ISSUE THREAD

**Issue by eatskolnikov** [developersdo/emplea_do#51]
**Comportamiento actual:**
- Si el job no ha sido aprobado solo sale un mensaje de "La posición está pendiente de aprobación"
- La persona que creó la posición no puede ver/revisar el detalle de la posición hasta que es aprobada

**Comportamiento deseado:**
- Permitir que se vea el trabajo sin aprobar
- La persona que lo creó debe poder ver el detalle de la posición aunque no haya sido publicada

**Comment by JhonasV** [comment]
Me gustaria tomar este issue

**Comment by eatskolnikov** [comment]
@JhonasV aún no hemos aplicado la parte de manejo de sesión pero puedes ir haciendo lo siguiente:
- En el endpoint de Jobs/Details agrega un parámetro de IsPreview
- En el servicio de jobs agrega un método de "GetDetails(int id, bool isPreview=false);
- En la lógica de GetDetails pon que en la búsqueda el compare algo como jobsList.Where(x=>x.Id=id && x.IsApproved == !isPreview);

You got it? Cuando me confirmes te lo asigno

**Comment by JhonasV** [comment]
Perfecto, I got it.
