### ISSUE TITLE
Add migrations for entities

### ISSUE THREAD

**Issue by eatskolnikov** [developersdo/emplea_do#66]
**Read the whole thing before starting 👇** 

- Add migrations for entities in the root of the Domain project, just the root.
- Add the table name as a constant
- One entity per migration file

Make sure to install the fluent migrator CLI tool
```sh
dotnet tool install -g FluentMigrator.DotNet.Cli
```

You **need** to compile the Migrations project before running the script

The command to run the migrations is bellow. You need to run it from the Migrations project folder. 

```sh
dotnet fm migrate -p sqlite -c "Data Source=../mydb.db" -a "bin/Debug/netcoreapp2.2/Migrations.dll"
```
This will create an SQLite Database in the root of the solution. 

Use any SQLite client you prefer to confirm the changes are applied.

**Comment by amaurygomez** [comment]
I will be working on this requirement.

**Comment by claudiosanchez** [comment]
@amaurygomez - Dime a ver? tienes un Pull request con esto ya? ¿Como puedo ayudarte?

**Comment by amaurygomez** [comment]
Buenas noches Claudio, estoy setiando FluentMigrator.Runner para automatizar el proceso manual de Fluent Migrator.
