### ISSUE TITLE
Configurar autenticación con github

### ISSUE THREAD

**Issue by eatskolnikov** [developersdo/emplea_do#70]
Cuando esté hecha por favor comentar el issue #49

**Comment by robertlluberes** [comment]
Me gustaría trabajar en este Issue.

Tengo una duda, el `ClientId` y el `ClientSecret` de los diferentes proveedores de autenticación, cuando se configuren ¿debería de estar en el archivo `appsettings`? https://github.com/developersdo/emplea_do/blob/0451c54e597f045ac7ac096287476ff7ef090988/Web/appsettings.Development.json#L12-L33

Entiendo que esa información es privada y deberia de ir en `secret`, ¿no?

**Comment by eatskolnikov** [comment]
@robertlluberes no, hay una instrucción en el readme.md para decirle a github que ignore los cambios en ese archivo
