### ISSUE TITLE
How can I access to the emplea.do's slack?

### ISSUE THREAD

**Issue by luis-ramirez** [developersdo/emplea_do#9]
Hi there, I was looking int the README how I can have access to the emplea.do's slack team and I haven't seen anything related to.

Is there any way to access there?

Thanks

**Comment by eatskolnikov** [comment]
@luis-ramirez We were creating invitations but they expire on 30 days so I'm setting up slackin so users can get unlimited invitations.

**Comment by eatskolnikov** [comment]
La url del Slack es https://empleado.slack.com
La url para crear una cuenta e invitar mas personas es http://bit.ly/empleadoslack

![screen shot 2018-08-21 at 12 56 02 am](https://user-images.githubusercontent.com/1693000/44381162-ff6e9e00-a4dc-11e8-80a7-4620d3473312.png)
